import{a as q,S as B,i as s}from"./assets/vendor-CIF6YjI2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const R="56194182-443121e89078ae09ebe47cc6e",E="https://pixabay.com/api/";async function p(t,o){return(await q.get(E,{params:{key:R,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),m=document.querySelector(".load-more"),M=new B(".gallery a",{captionsData:"alt",captionDelay:250});function h(t){const o=t.map(({webformatURL:n,largeImageURL:c,tags:e,likes:r,views:a,comments:P,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${c}">
          <img class="gallery-image" src="${n}" alt="${e}" />
        </a>
        <div class="gallery-info">
          <p><b>Likes</b><span>${r}</span></p>
          <p><b>Views</b><span>${a}</span></p>
          <p><b>Comments</b><span>${P}</span></p>
          <p><b>Downloads</b><span>${v}</span></p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",o),M.refresh()}function $(){f.innerHTML=""}function y(){g.classList.remove("hidden")}function b(){g.classList.add("hidden")}function L(){m.classList.remove("hidden")}function l(){m.classList.add("hidden")}const w=document.querySelector(".form"),O=document.querySelector(".load-more"),x=15;let u="",i=1,d=0;w.addEventListener("submit",A);O.addEventListener("click",H);async function A(t){t.preventDefault();const o=t.currentTarget.elements["search-text"].value.trim();if(!o){s.warning({message:"Please enter a search query!",position:"topRight"});return}u=o,i=1,d=0,$(),l(),y();try{const n=await p(u,i);if(d=n.totalHits,n.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(n.hits),S()?(l(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{s.error({message:"Something went wrong. Please try again later!",position:"topRight"})}finally{b(),w.reset()}}async function H(){i+=1,l(),y();try{const t=await p(u,i);h(t.hits),_(),S()?(l(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{s.error({message:"Something went wrong. Please try again later!",position:"topRight"})}finally{b()}}function S(){return i*x>=d}function _(){const t=document.querySelector(".gallery-item");if(!t)return;const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
